name: CI

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4.4.0
      - name: Set up Go
        uses: actions/setup-go@40f1582b2485089dde7abd97c1529aa768e1baff # v5.6.0
        with:
          go-version: "1.27.x"
      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@9fae48acfc02a90574d7c304a1758ef9895495fa # v7.0.1

  build:
    name: Build and test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: ["1.27.x"]
    env:
      VERBOSE: 1

    steps:
      - name: Checkout code
        uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4.4.0
      - name: Set up Go
        uses: actions/setup-go@40f1582b2485089dde7abd97c1529aa768e1baff # v5.6.0
        with:
          go-version: ${{ matrix.go-version }}
      - name: Install tparse
        run: go install github.com/mfridman/tparse@main
      - name: Build
        run: go build -v .
      - name: Run tests
        shell: bash
        run: |
          go test $(go list ./... | grep -v 'examples') -count=1 -v -json -cover \
            | tparse -all -follow -sort=elapsed -trimpath=auto
